# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "CI"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            mmodolo/rotten-potatoes:latest
            mmodolo/rotten-potatoes:v${{ github.run_number }}
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}
          # If your kubeconfig has multiple contexts, use this field to use a specific context, otherwise the default one would be chosen
          context: # optional
          # Cluster Url
          k8s-url: # optional
          # Service account secret (run kubectl get serviceaccounts <service-account-name> -o yaml and copy the service-account-secret-name)
          k8s-secret: # optional
          # Token extracted from the secret of service account (should be base 64 decoded)
          token: # optional
          # Azure resource group name
          resource-group: # optional
          # Azure connected cluster name
          cluster-name: # optional
